## I ran into some software installation problems that I was struggling to fix, so there isn't much of this that I was able to do in time.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path
import random
import torch
import torchvision.datasets as datasets
import scipy


In [3]:
mnist_trainset = datasets.MNIST(root='./MNIST_data', train=True, download=True, transform=None)
mnist_testset = datasets.MNIST(root='./MNIST_data', train=False, download=True, transform=None)


100%|███████████████████████████| 9912422/9912422 [00:00<00:00, 18285301.79it/s]


Extracting ./MNIST_data/MNIST/raw/train-images-idx3-ubyte.gz to ./MNIST_data/MNIST/raw



100%|███████████████████████████████| 28881/28881 [00:00<00:00, 21111135.21it/s]


Extracting ./MNIST_data/MNIST/raw/train-labels-idx1-ubyte.gz to ./MNIST_data/MNIST/raw



100%|████████████████████████████| 1648877/1648877 [00:00<00:00, 6294870.91it/s]


Extracting ./MNIST_data/MNIST/raw/t10k-images-idx3-ubyte.gz to ./MNIST_data/MNIST/raw



100%|██████████████████████████████████| 4542/4542 [00:00<00:00, 3998012.33it/s]

Extracting ./MNIST_data/MNIST/raw/t10k-labels-idx1-ubyte.gz to ./MNIST_data/MNIST/raw



In [77]:
mnist_trainset[33426]


(<PIL.Image.Image image mode=L size=28x28 at 0x7F82B1A303D0>, 4)

In [71]:

# TRAINING:
# shuffle through training images,
# reshape to 781 X 1 vector input.
# Initialize weights (gaussian)
# compute loss function for each points
# compute gradient for that point
# update weights



In [ ]:
def Train(TrainingSet, LearningRate, Epochs, W1, W2, W3):
    
    log_softmax = torch.nn.Softmax(dim = 1)
    
    for epoch in Epochs:
        for i in range(len(TrainingSet)):
            x = torch.reshape(TrainingSet[i][0], (1,784))
            x1 = torch.sigmoid(torch.matmul(x, W1))
            x2 = torch.sigmoid(torch.matmul(x1,W2))
            y_hat = log_softmax(torch.matmul(x2,W3))
            Loss = -1*y_hat[TrainingSet[i][1]]
#           -1*torch.sum(TrainingSet[i][1]*y_hat)
            
            

In [ ]:
def UpdateWeights():
    pass

In [3]:
# use first pass weight intialization as all zeros
# x = torch.zeros(1,784)
weights1 = torch.randn(784,300)
weights2 = torch.randn(300,200)
weights3 = torch.randn(200,10)
# torch.matmul(weights2, weights3)
# len(weights1)
# torch.matmul(x,weights1).shape
weights3

tensor([[-0.3450,  0.4845,  0.6976,  ..., -0.1667,  0.7494,  0.4272],
        [-1.5239,  0.3228, -0.0256,  ...,  1.3976,  0.8027, -0.7781],
        [ 0.2674, -0.6134, -0.0870,  ..., -0.5484, -1.2196,  0.6618],
        ...,
        [ 0.0375,  0.4429, -0.1458,  ...,  0.1587,  0.0730,  0.6804],
        [-1.0778, -0.5875, -1.0598,  ..., -0.9150, -0.9983, -0.9036],
        [-0.4043, -1.3610,  1.1925,  ...,  1.4834, -1.5107, -0.5756]])

In [53]:
tensor1 = torch.randn(1,5)

# log_softmax(tensor1)
tensor1

tensor([[ 1.7699,  0.8489,  0.0099, -1.2067, -1.2578]])

In [54]:
log_softmax(tensor1)

tensor([[0.5990, 0.2385, 0.1030, 0.0305, 0.0290]])

In [69]:
x = torch.tensor([1,2,3,4,5,100])
x = torch.reshape(x,(3,2))
x

tensor([[  1,   2],
        [  3,   4],
        [  5, 100]])

In [70]:
x = torch.reshape(x,(1,6))
torch.sigmoid(x)

tensor([[0.7311, 0.8808, 0.9526, 0.9820, 0.9933, 1.0000]])

# Using the packages